api:
  host: 'localhost'
  port: '3000'
  jwtSecret: 'thisWillBeSecret'
database:
  host: 'database host'
  port: 'database port'
  database: 'database name'
  username: 'database username'
  password: 'database password'